#! /bin/sh


#Autostart
nitrogen --restore &
sxhkd &
picom --config $HOME/.config/picom/picom.conf &
$HOME/.config/polybar/launch.sh



bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Alacritty desktop='^1' follow=on
bspc rule -a firefox desktop='^2' follow=on
bspc rule -a dolphin desktop='^3' follow=on
bspc rule -a VSCodium desktop='^4' follow=on
bspc rule -a vlc desktop='^5' follow=on
bspc rule -a Pix desktop='^6' follow=on
bspc rule -a Spotify desktop='^7' follow=on
bspc rule -a discord desktop='^8' follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
